INSERT INTO players (name) VALUES ('Alexander');
INSERT INTO players (name) VALUES ('Emily');
INSERT INTO players (name) VALUES ('Michael');
INSERT INTO players (name) VALUES ('Anastasia');
INSERT INTO players (name) VALUES ('David');
INSERT INTO players (name) VALUES ('Katherine');
INSERT INTO players (name) VALUES ('Ivan');
INSERT INTO players (name) VALUES ('Sophia');
INSERT INTO players (name) VALUES ('Nicholas');
INSERT INTO players (name) VALUES ('Victoria');
INSERT INTO players (name) VALUES ('Sergey');
INSERT INTO players (name) VALUES ('Mary');
INSERT INTO players (name) VALUES ('Andrew');
INSERT INTO players (name) VALUES ('Catherine');
INSERT INTO players (name) VALUES ('Vladimir');
INSERT INTO players (name) VALUES ('Julia');
INSERT INTO players (name) VALUES ('Paul');
INSERT INTO players (name) VALUES ('Natalie');
INSERT INTO players (name) VALUES ('Constantine');
INSERT INTO players (name) VALUES ('Olivia');
INSERT INTO matches (player1_id, player2_id, winner_id)values (1, 2, 1);
INSERT INTO matches (player1_id, player2_id, winner_id)values (3, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) values (5, 6, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) values (7, 8, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) values (9, 10, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) values (11, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) values (13, 14, 14);
INSERT INTO matches (player1_id, player2_id, winner_id) values (15, 16, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) values (17, 18, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) values (19, 20, 20);
